# Generated by Django 3.2.6 on 2021-10-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitsi_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jitsi_Websocket_Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_in_function', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_for_user', models.CharField(blank=True, max_length=255, null=True)),
                ('error_text', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Errors',
                'ordering': ['-created'],
            },
        ),
    ]
